//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTAssignmentt4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int PrimaryCategoryId { get; set; }
        public string ProductDescription { get; set; }
        public bool Active { get; set; }
        public decimal ProductPrice { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
